<?php

/**
 * @file
 * Main file for the Save Draft module, which adds a 'Save as draft' button to content types.
 */
 
 /**
  * Implements hook_perm().
  */
 
 function save_draft_perm() {
   return array('save draft');
 }

/**
 * Implements hook_form_alter().
 */
 
function save_draft_form_alter(&$form, &$form_state, $form_id) {
  $form_id = substr($form_id, -9);
  if ($form_id == 'node_form' && user_access('save draft')) {
    $form['options']['status'] = false;
    if (empty($form['#validate'])) {
      $form['#validate'] = array();
    }
    array_unshift($form['#validate'], 'save_draft_validate');
    if (isset($form['nid']['#value'])) {
      if ($form['#node']->status == 1) {
        $form['buttons']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Unpublish'),
          '#weight' => '9',
          '#submit' => array('save_draft_submit')
        );
        $form['buttons']['submit']['#value'] = t('Save');
      }
      else {
        $form['buttons']['draft'] = array(
          '#type' => 'submit',
          '#class' => 'form-submit',
          '#value' => t('Save'),
          '#weight' => '0',
		  '#submit' => array('save_draft_submit')
        );
        $form['buttons']['submit']['#value'] = t('Publish');
      }
    }
    else {
      $form['buttons']['draft'] = array(
        '#type' => 'submit',
        '#class' => 'form-submit',
        '#value' => t('Save as draft'),
        '#weight' => '9',
        '#submit' => array('save_draft_submit')
      );
      $form['buttons']['submit']['#value'] = t('Publish');
    }
  }
}

/**
 * Handles save draft form validation
 */
function save_draft_validate($form, &$form_state) {
  // Set the node to be published or unpublished depending on which button was
  // clicked.
  if ($form_state['clicked_button']['#value'] == $form['buttons']['draft']['#value']) {
    $form_state['values']['status'] = 0;
  }
  elseif ($form_state['clicked_button']['#value'] == $form['buttons']['submit']['#value']) {
    $form_state['values']['status'] = 1;
  }
}

/**
 * Handles save draft form submission
 */
function save_draft_submit($form, &$form_state) {
  node_form_submit($form, $form_state);
}
